name: Node.js Package

on:
#  push:
#    branches:
#      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn ci
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn config set -H "npmRegistries['$(yarn config get npmRegistryServer)'].npmAuthToken" "$NODE_AUTH_TOKEN" && yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
